### ISSUE TITLE
error to install on python3.8/windows x64

### ISSUE THREAD

**Issue by wjiang100** [whosaysni/robotframework-seriallibrary#15]
```
> C:\Users\admin\AppData\Local\Programs\Python\Python38\Scripts>pip install robotframework-seriallibrary==0.2.1
> Collecting robotframework-seriallibrary==0.2.1
>   Using cached robotframework-seriallibrary-0.2.1.tar.gz (8.1 kB)
>   Preparing metadata (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: 'c:\users\admin\appdata\local\programs\python\python38\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-x4njfoo7\\robotframework-seriallibrary_dfb9d411782242eab3e2d406420ceea0\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-x4njfoo7\\robotframework-seriallibrary_dfb9d411782242eab3e2d406420ceea0\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\admin\AppData\Local\Temp\pip-pip-egg-info-6_mll9me'
>        cwd: C:\Users\admin\AppData\Local\Temp\pip-install-x4njfoo7\robotframework-seriallibrary_dfb9d411782242eab3e2d406420ceea0\
>   Complete output (15 lines):
>   C:\Users\admin\AppData\Local\Temp\pip-install-x4njfoo7\robotframework-seriallibrary_dfb9d411782242eab3e2d406420ceea0\setup.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>     from imp import load_source
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "C:\Users\admin\AppData\Local\Temp\pip-install-x4njfoo7\robotframework-seriallibrary_dfb9d411782242eab3e2d406420ceea0\setup.py", line 21, in <module>
>       VERSION = load_source(
>     File "c:\users\admin\appdata\local\programs\python\python38\lib\imp.py", line 171, in load_source
>       module = _load(spec)
>     File "<frozen importlib._bootstrap>", line 702, in _load
>     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>     File "<frozen importlib._bootstrap_external>", line 844, in exec_module
>     File "<frozen importlib._bootstrap_external>", line 980, in get_code
>     File "c:\users\admin\appdata\local\programs\python\python38\lib\imp.py", line 152, in get_data
>       self.file = file = open(self.path, 'rb')
>   FileNotFoundError: [Errno 2] No such file or directory: 'version'
>   ----------------------------------------
> WARNING: Discarding https://files.pythonhosted.org/packages/ea/04/a07a8b0008eb8300c33644058c128093edad019f36bb63f230857fd17918/robotframework-seriallibrary-0.2.1.tar.gz#sha256=1b478b713e84ab1947e47570ce855f4c997ba3302760f34a2a16c5bf58c0be8c (from https://pypi.org/simple/robotframework-seriallibrary/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Could not find a version that satisfies the requirement robotframework-seriallibrary==0.2.1 (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.4, 0.3.1)
> ERROR: No matching distribution found for robotframework-seriallibrary==0.2.1
```

**Comment by whosaysni** [comment]
Thank you for posting issue, and terribly sorry for long absense.
0.4.1 should fix it -- annoying version.py file has been removed.
If you still have trouble, please reopen.
